version: '3'
services: 
  web:
    environment: 
      - CHOKIDAR_USEPOLLING=true
      - COMPOSE_CONVERT_WINDOWS_PATHS=1
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
    - "3000:3000"
